// Code generated by qtc from "export.sql". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line export/export.sql:1
package export

//line export/export.sql:1
import "github.com/Jiang-Gianni/gosqlx/rdms"

//line export/export.sql:2
import "strings"

//line export/export.sql:4
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line export/export.sql:4
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line export/export.sql:4
func StreamExportSql(qw422016 *qt422016.Writer, qr *rdms.QueryResults, insertIntoTable string) {
//line export/export.sql:4
	qw422016.N().S(`INSERT INTO `)
//line export/export.sql:4
	qw422016.E().S(insertIntoTable)
//line export/export.sql:4
	qw422016.N().S(`(`)
//line export/export.sql:4
	qw422016.E().S(strings.Join(qr.Columns, ", "))
//line export/export.sql:4
	qw422016.N().S(`) VALUES `)
//line export/export.sql:4
	for i, row := range qr.Rows {
//line export/export.sql:4
		qw422016.N().S(`
('`)
//line export/export.sql:5
		qw422016.N().S(strings.Join(row, "', '"))
//line export/export.sql:5
		qw422016.N().S(`')`)
//line export/export.sql:5
		if len(qr.Rows) > 0 && i != len(qr.Rows)-1 {
//line export/export.sql:5
			qw422016.N().S(`,`)
//line export/export.sql:5
		} else {
//line export/export.sql:5
			qw422016.N().S(`;`)
//line export/export.sql:5
		}
//line export/export.sql:5
	}
//line export/export.sql:5
	qw422016.N().S(`
`)
//line export/export.sql:6
}

//line export/export.sql:6
func WriteExportSql(qq422016 qtio422016.Writer, qr *rdms.QueryResults, insertIntoTable string) {
//line export/export.sql:6
	qw422016 := qt422016.AcquireWriter(qq422016)
//line export/export.sql:6
	StreamExportSql(qw422016, qr, insertIntoTable)
//line export/export.sql:6
	qt422016.ReleaseWriter(qw422016)
//line export/export.sql:6
}

//line export/export.sql:6
func ExportSql(qr *rdms.QueryResults, insertIntoTable string) string {
//line export/export.sql:6
	qb422016 := qt422016.AcquireByteBuffer()
//line export/export.sql:6
	WriteExportSql(qb422016, qr, insertIntoTable)
//line export/export.sql:6
	qs422016 := string(qb422016.B)
//line export/export.sql:6
	qt422016.ReleaseByteBuffer(qb422016)
//line export/export.sql:6
	return qs422016
//line export/export.sql:6
}
