// Code generated by qtc from "z.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// <!DOCTYPE html>
// <html>
//
// <head>
//     <title>SQL Client</title>
//     <link rel="stylesheet" href="./assets/pico.css">
//     <style>
//         body {
//             font-family: Arial, sans-serif;
//         }
//
//         #menu {
//             float: left;
//             width: 20%;
//             background-color: #333;
//             color: white;
//             padding: 10px;
//         }
//
//         #content {
//             margin-left: 25%;
//             padding: 20px;
//         }
//
//         #query {
//             width: 100%;
//             height: 150px;
//         }
//
//         #result {
//             width: 100%;
//             border: 1px solid #ccc;
//             padding: 10px;
//             margin-top: 10px;
//         }
//     </style>
// </head>
//
// <body>
//
//     <div id="menu">
//         <h2>Tables and Views</h2>
//         <ul>
//             <li>Table 1</li>
//             <li>Table 2</li>
//             <li>View 1</li>
//             <li>View 2</li>
//         </ul>
//     </div>
//
//     <div id="content">
//         <h2>SQL Query</h2>
//         <textarea id="query" placeholder="Enter your SQL query here"></textarea>
//         <button id="execute">Execute</button>
//
//         <h2>Query Result</h2>
//         <div id="result">
//             <!-- Query result will be displayed here -->
//         </div>
//     </div>
//
//     <script>
//         // You will need JavaScript to handle user interactions and AJAX requests to execute SQL queries and display results.
//         // This is a basic structure for the HTML, and you will need to implement the functionality.
//         document.getElementById('execute').addEventListener('click', function () {
//             // Add code to send the SQL query to the server, execute it, and display the result here.
//         });
//     </script>
// </body>
//
// </html>

//line z.html:71
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line z.html:71
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

