// Code generated by qtc from "database.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line views/database.html:1
package views

//line views/database.html:1
import "github.com/Jiang-Gianni/gosqlx/db"

//line views/database.html:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/database.html:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/database.html:3
func StreamDatabaseBody(qw422016 *qt422016.Writer, conn db.Connection, tables []string) {
//line views/database.html:3
	qw422016.N().S(`

<div>
    `)
//line views/database.html:6
	qw422016.N().S(databaseSideMenu(tables))
//line views/database.html:6
	qw422016.N().S(`
</div>

`)
//line views/database.html:9
}

//line views/database.html:9
func WriteDatabaseBody(qq422016 qtio422016.Writer, conn db.Connection, tables []string) {
//line views/database.html:9
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/database.html:9
	StreamDatabaseBody(qw422016, conn, tables)
//line views/database.html:9
	qt422016.ReleaseWriter(qw422016)
//line views/database.html:9
}

//line views/database.html:9
func DatabaseBody(conn db.Connection, tables []string) string {
//line views/database.html:9
	qb422016 := qt422016.AcquireByteBuffer()
//line views/database.html:9
	WriteDatabaseBody(qb422016, conn, tables)
//line views/database.html:9
	qs422016 := string(qb422016.B)
//line views/database.html:9
	qt422016.ReleaseByteBuffer(qb422016)
//line views/database.html:9
	return qs422016
//line views/database.html:9
}

//line views/database.html:12
func streamdatabaseSideMenu(qw422016 *qt422016.Writer, tables []string) {
//line views/database.html:12
	qw422016.N().S(`

<article>
    <div class="collapse-title">
        Tables
    </div>
    <div>
        <ul class="menu">
            `)
//line views/database.html:20
	for _, table := range tables {
//line views/database.html:20
		qw422016.N().S(`
            <li class="border-2 border-teal-500 m-1 rounded text-teal-300">
                <div hx-push-url="true" hx-get="?table=`)
//line views/database.html:22
		qw422016.E().S(table)
//line views/database.html:22
		qw422016.N().S(`">`)
//line views/database.html:22
		qw422016.E().S(table)
//line views/database.html:22
		qw422016.N().S(`</div>
            </li>
            `)
//line views/database.html:24
	}
//line views/database.html:24
	qw422016.N().S(`
        </ul>

    </div>
</article>

`)
//line views/database.html:30
}

//line views/database.html:30
func writedatabaseSideMenu(qq422016 qtio422016.Writer, tables []string) {
//line views/database.html:30
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/database.html:30
	streamdatabaseSideMenu(qw422016, tables)
//line views/database.html:30
	qt422016.ReleaseWriter(qw422016)
//line views/database.html:30
}

//line views/database.html:30
func databaseSideMenu(tables []string) string {
//line views/database.html:30
	qb422016 := qt422016.AcquireByteBuffer()
//line views/database.html:30
	writedatabaseSideMenu(qb422016, tables)
//line views/database.html:30
	qs422016 := string(qb422016.B)
//line views/database.html:30
	qt422016.ReleaseByteBuffer(qb422016)
//line views/database.html:30
	return qs422016
//line views/database.html:30
}
