// Code generated by qtc from "error.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line views/error.html:1
package views

//line views/error.html:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/error.html:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/error.html:1
func StreamError(qw422016 *qt422016.Writer, err error) {
//line views/error.html:1
	qw422016.N().S(`
<div>
    Error: `)
//line views/error.html:3
	qw422016.E().S(err.Error())
//line views/error.html:3
	qw422016.N().S(`
</div>
`)
//line views/error.html:5
}

//line views/error.html:5
func WriteError(qq422016 qtio422016.Writer, err error) {
//line views/error.html:5
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/error.html:5
	StreamError(qw422016, err)
//line views/error.html:5
	qt422016.ReleaseWriter(qw422016)
//line views/error.html:5
}

//line views/error.html:5
func Error(err error) string {
//line views/error.html:5
	qb422016 := qt422016.AcquireByteBuffer()
//line views/error.html:5
	WriteError(qb422016, err)
//line views/error.html:5
	qs422016 := string(qb422016.B)
//line views/error.html:5
	qt422016.ReleaseByteBuffer(qb422016)
//line views/error.html:5
	return qs422016
//line views/error.html:5
}
