// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package db

import (
	"database/sql"
)

type Connection struct {
	ID         int64
	IDRdms     int64
	Ssl        sql.NullBool
	Name       string
	Host       string
	Port       int64
	Datasource string
	User       string
	Password   string
}

type Rdm struct {
	ID     int64
	System string
}
