// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1
// source: rdms.sql

package db

import (
	"context"
)

const fillRdms = `-- name: FillRdms :exec
insert into rdms(id, system) values (1, 'PostgreSQL')
`

func (q *Queries) FillRdms(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, fillRdms)
	return err
}
